name: E2E Tests

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [ opened, synchronize, reopened ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group:  ci-e2e-docker-maven-plugin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        java-version: [ 17 ]
        python-version: [ '3.10' ]
        node-version: [ 14 ]


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up jdk ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get release notes
        id: config
        run: |
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_version.sh)

      - name: Output release notes
        run: |
          echo "${{ steps.config.outputs.GIT_RELEASE_NOTES }}"
          echo CURRENT_VERSION="${{ steps.config.outputs.CURRENT_VERSION }}"

      - name: Cache maven packages
        uses: actions/cache@v3.0.8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Everything
        run: |
          mvn ${MAVEN_ARGS} clean install -DskipTests -Djacoco.skip=true

      - name: Start the stack
        run: |
          cd environment/local
          docker-compose up -d

      - name: Wait for CMS to start
        run: |
          echo "Waiting for bundles to be installed"
          export LOGIN="wsadmin:wsadmin"
          export ADDRESS="http://0.0.0.0:8080"
          export INSTALL_CHECK="/system/console/bundles.json"
          echo "curl -u $LOGIN --header Referer:${ADDRESS} --silent --connect-timeout 5 --max-time 5 ${ADDRESS}${INSTALL_CHECK} | grep -q \"state\":\"Installed\" && echo true || echo false"

          echo "Wait: "
          echo -n "." ""
          while [[ "true" == "$(curl -L -u "$LOGIN" --header "Referer:${ADDRESS}" --silent -N --connect-timeout 5 --max-time 5 "${ADDRESS}${INSTALL_CHECK}" | grep -q "\"state\":\"Installed\"" && echo true || echo false)" ]]; do
              echo -n "." ""
              $SLEEP 1
          done
          echo "" ""

          echo "Bundles are installed"


      - name: Install test content
        run: |
          cd tests/content
          mvn clean install -P autoInstallBundle

      - name: Run Automation tests
        run: |
          cd tests/end-to-end
          npm install
          export APP_IP=$(docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}')"
          echo APP_IP=${APP_IP}
          curl -vL -u wsadmin:wsadmin http://0.0.0.0:8080
          curl -vL -u wsadmin:wsadmin http://127.0.0.1:8080
          curl -vL -u wsadmin:wsadmin http://${APP_IP}:8080
          CYPRESS_BASE_URL=http://${APP_IP}:8080 npm run test

      - name: Stop the stack
        run: docker-compose down

      - name: Automation test if failure
        run: |
          df
          docker ps -a
          cd environment/local
          docker-compose down
        if: failure()

